### ISSUE TITLE
Integrate new design for tutorial pages

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#100]
[html_and_css.zip](https://github.com/hasadna/sensory-interface/files/4586957/html_and_css.zip)

**Comment by oferb** [comment]
Tomer, you're awesome!
Please consult with @mohammad-suliman on this one.

**Comment by oferb** [comment]
Discussion points for @mohammad-suliman 
* Links should link to the correct places
* Page should be separated to landmarks correctly
* We should check that page get 100 on accessibility test in Chrome DevTools.
* The main heading for the page content should be defined as H1.

**Comment by BitanTomer** [comment]
@oferb I don't have permission to the google drive

**Comment by oferb** [comment]
Fonts should be Sans Serif in Hebrew and English

**Comment by oferb** [comment]
@BitanTomer Done :)
