### ISSUE TITLE
Make language selection a button

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#110]
This button can open a menu for language selection.
Tab or arrow will move through languages, enter key will select.

**Comment by S0AndS0** [comment]
`select` and `option` elements might be better for cross-browser support, however, there are restrictions on how these elements can be styled, [StackOverflow -- How to style the option of an html “select” element?](https://stackoverflow.com/questions/7208786/) goes into more detail on that.

Probably the for consistent styling the better option would be to use radio inputs.

**Comment by oferb** [comment]
There's already a rectangle. We just need to make it more prominent. I think we can use this: `:focus`.
