### ISSUE TITLE
Increase contrast in background

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#111]

**Comment by S0AndS0** [comment]
Also I noticed that the main site is slightly different than what is served via [GitHub Pages](https://s0ands0.github.io/sensory-interface/), and believe that making this project friendlier for GitHub Pages to host will mitigate issues of the main site becoming synchronized. Here's a bit about custom URLs in regards to GitHub Pages that may be of use...

https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by oferb** [comment]
We're not interested in hosting our site on GitHub Pages.
We already host it on Firebase Hosting.

**Comment by S0AndS0** [comment]
Firebase hosted content, last I checked, is not in-sync with latest changes to site source. Which leads me to believe that something about deployment with Firebase isn't fully automated.

If my suspensions about Firebase are correct

- Then the simplest and most sustainable solution would be utilizing GitHub Pages, even if site files are pre-built.

- Or the next option would be utilizing GitHub Actions to trigger Firebase updates. However, that'd make on-boarding much more difficult for contributors as itd require each individual to setup an account with Firebase, as well as fiddle with GitHub Action Secrets.

**Comment by oferb** [comment]
That's true, deployment is manual.
I think it's better than way, since we can choose to deploy at certain times, not necessarily when we push to master.

But this conversation is off-topic to the issue at hand, which deals with background.

**Comment by S0AndS0** [comment]
Automating the deployment would mitigate issues of changes to style not showing up.

Also what happened to the desires expressed in Issue #26 where ya had wanted to have every branch deployed? Seems rather inconsistent to me to want automation one month and then prefer manual deployment on another.

As for the background in particular, the Minima theme from Jekyll doesn't suffer from any contrast issues, and isn't difficult to customize.

**Comment by oferb** [comment]
> Automating the deployment would mitigate issues of changes to style not showing up.
This is not related to deployment, but rather to just setting up proper contrast.

> Also what happened to the desires expressed in Issue #26 
That's referring to dev deployment, not prod deployment.
