### ISSUE TITLE
Fix focused element highlight

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#112]
Focused elements get a highlighted rectangle.
Make this rectangle stand out more visually.

**Comment by S0AndS0** [comment]
Pretty sure that can be done entirely with the `:active` CSS pseudo class, check [Mozilla developer -- `:active`](https://developer.mozilla.org/en-US/docs/Web/CSS/:active) for examples.

**Comment by oferb** [comment]
Yep, either that or `:focus`:
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus
