### ISSUE TITLE
Set appropriate H levels

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#114]
For example: "Go to our tutorial" should not be H.

**Comment by S0AndS0** [comment]
This can be done via MarkDown...

```MarkDown
# Heading level one

## Heading level two

### Heading level three
```

... that compiles to HTML...

```HTML
<h1>Heading level one</h1>

<h2>Heading level two</h2>

<h3>Heading level three</h3>
```

**Comment by oferb** [comment]
This is on our main page, which is not markdown.
Only docs are markdown.

**Comment by S0AndS0** [comment]
There seems to be MarkDown files that are being compiled to HTML, within the [`public/english_guides`](https://github.com/hasadna/sensory-interface/tree/master/public/english_guides) and [`public/hebrew_guides`](https://github.com/hasadna/sensory-interface/tree/master/public/hebrew_guides) directories. To me it would make sence to either write everything in MarkDown and auto-compile to HTML.. or write everything in HTML

**Comment by oferb** [comment]
We can have some pages auto-compile and some pages written in HTML.

:)

**Comment by S0AndS0** [comment]
What tools are you utilizing to auto-compile? I ask because last I heard from you via non-public chat, you had stated that @mohammad-suliman was forced to do this manually.

**Comment by oferb** [comment]
Should have written compile, not auto-compile.

**Comment by S0AndS0** [comment]
Hmm, again I'll encourage you to research automation for building HTML from Markdown sources, even if it's not Jekyll, some form of automation would be better than squandering the time and talents of developers with manual transpiling.
