### ISSUE TITLE
Allow user to select stock

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#129]
This is on the stocks page.

**Comment by S0AndS0** [comment]
Might be a good idea to add perma-link(s) to the relevant source code

**Comment by oferb** [comment]
Sometimes I create issues for Mohammad and myself, and we know the relevant source code.

I'm just trying to save some effort for myself. There's enough issues in the repo with enough context. If you think this might be an issue you wanna tackle, I'd be happy to elaborate. In general though, I only post enough context to:
- Not forget what the issue is about
- The person currently planned to take it on will understand it.

**Comment by mohammad-suliman** [comment]
Fixed
