### ISSUE TITLE
Graph scan

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#153]
Allow values to be played in sequence.

User inputs:
I believe a “scan” function is mandatory.  That would give the user an immediate global perspective on the graph at hand;
lower frequencies are quite difficult to hear

שהמשתמש ישמע את התאריך והערך שבו מתחיל הגרף, את כל המנגינה השלמה של העליות/ירידות שלאורך כל הגרף, ולבסוף את התאריך והערך שבו מסתיים הגרףע

**Comment by mohammad-suliman** [comment]
Fixed by #177
