### ISSUE TITLE
Query Strings within URLs can be logged by server(s)

### ISSUE THREAD

**Issue by S0AndS0** [hasadna/accessible-graphs#44]
So far I've not found a need for remote server(s) to have access to client data, nor have I found any warnings for clients to review about data being transmitted when utilizing this project.

If anyone uses this project without https (or improperly configured SSL), then data could be intercepted and/or manipulated during transit.

If the server is ever compromised any data sent could be logged and/or re-transmitted.

If a client submits malformed data via query strings, then this project could become apart of a reflection attack; meaning that clients would initially attribute their browser's compromise to this project and/or server(s) hosting this project.

If query strings continue to be used and a client submits private information, then server admins utilizing this project may become liable for any damages caused by that information being; intercepted, logged without consent, or shared.

I believe we should investigate how to use `localStorage` and/or `sessionStorage` so that client information is **never** transmitted by this project.

In the meantime I believe this project **must** provide some form of warning to clients so that they are made aware of how insecure query strings are.

**Comment by oferb** [comment]
I think your `public/privacy.html` in #81 addresses this right?

In general links should be shareable so in some way the info needs to be encoded in the link.
Otherwise you need a server to broker the info transfer and that has its own problems right?

**Comment by S0AndS0** [comment]
The PR's privacy notice is an attempt at beginning to address this issue.

If this project where to become a browser plugin, or like ya had suggested a service-worker, I think the whole issue of transmitting data could be squashed. But until something like that is implemented I believe that clients need to be made aware of privacy trade-offs that have been made.

**Comment by oferb** [comment]
That will help when copy-pasting the data, but that still won't help with shareable links though..

We could actually do something a little better without service workers - an SPA where it changes the data and the URL, but only locally.

If you refresh, it will still send that data in the url to the server though.

**Comment by S0AndS0** [comment]
Considering that page reload would put this project back into the same situation that it is now, I'd not pursue SPA as an option.

Currently I think that moving towards browser plugin(s) based solution is going to be the best option for security, privacy, and maintainability.

Keeping the current features may still be an option for sharing between clients, but that'd still require some form of privacy/security notice.
