### ISSUE TITLE
Unhide hamburger button and try to make it accessible

### ISSUE THREAD

**Issue by oferb** [hasadna/accessible-graphs#87]

**Comment by oferb** [comment]
Consider using Eilana's website example:
https://adn-accesstime.com/

**Comment by S0AndS0** [comment]
The `jekyll/minima` theme has a mobile friendly menu that doesn't require any JavaScript, here's an old that also resolves collapsing the menu when a client clicks anywhere outside of an opened menu...

https://github.com/jekyll/minima/pull/405
